# Generated by Django 4.1 on 2022-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.PositiveIntegerField(default=1, verbose_name='money'),
        ),
    ]
