# Generated by Django 4.1 on 2022-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_age_customuser_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='money',
            field=models.PositiveIntegerField(default=0, verbose_name='money'),
        ),
    ]
