# Generated by Django 4.1 on 2022-09-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='phone'),
        ),
    ]
