# Generated by Django 4.1 on 2022-09-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dramatic_name',
            field=models.CharField(blank=True, max_length=70, verbose_name='dramatic name'),
        ),
    ]
