# Generated by Django 4.1 on 2022-09-30 19:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('azbankgateways', '0005_alter_bank_status'),
        ('products', '0010_alter_product_datetime_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_order', to='products.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='name')),
                ('last_name', models.CharField(max_length=50, verbose_name='family')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]')], verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('n', models.CharField(max_length=10)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='azbankgateways.bank', verbose_name='payment')),
                ('products', models.ManyToManyField(related_name='order', to='orders.productorder', verbose_name='products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
