# Generated by Django 4.1 on 2022-09-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='n',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
