# Generated by Django 4.1 on 2022-10-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
