# Generated by Django 4.1 on 2022-09-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
