# Generated by Django 4.1 on 2022-09-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-active',)},
        ),
    ]
