# Generated by Django 4.1 on 2022-09-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DateTime of creation'),
        ),
    ]
